/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package html.editor;

import java.io.File;
import java.io.FileWriter;
import javax.swing.JFileChooser;
import javax.swing.text.StyledEditorKit;
import javax.swing.text.html.HTMLEditorKit;
import javax.swing.text.rtf.RTFEditorKit;

/**
 *
 * @author TOAN
 */
public class AppMain extends javax.swing.JFrame {

    /**
     * Creates new form AppMain
     */
    public AppMain() {
        initComponents();
        this.setLocation(300, 100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jFileChooser = new javax.swing.JFileChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        htmlEditor = new javax.swing.JEditorPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        mnuOpen = new javax.swing.JMenuItem();
        mnuSave = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnuHtml = new javax.swing.JRadioButtonMenuItem();
        mnuPlain = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HTML Editor");

        htmlEditor.setEditorKit(null);
        htmlEditor.setText("<html>\n<head>\n</head>\n<body>\n<p>\nThis is HTML Editor created by <b>FPT-Aptech</b> students.\n</p>\n<p color=\"red\">\n<b>Java is beautiful</b>\n</p>\n</body>\n</html>");
        jScrollPane2.setViewportView(htmlEditor);

        jMenu3.setText("File");

        mnuOpen.setText("Open");
        mnuOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuOpenActionPerformed(evt);
            }
        });
        jMenu3.add(mnuOpen);

        mnuSave.setText("Save");
        mnuSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSaveActionPerformed(evt);
            }
        });
        jMenu3.add(mnuSave);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");

        buttonGroup1.add(mnuHtml);
        mnuHtml.setText("HTML");
        mnuHtml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHtmlActionPerformed(evt);
            }
        });
        jMenu4.add(mnuHtml);

        buttonGroup1.add(mnuPlain);
        mnuPlain.setSelected(true);
        mnuPlain.setText("Plain");
        mnuPlain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPlainActionPerformed(evt);
            }
        });
        jMenu4.add(mnuPlain);

        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuHtmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHtmlActionPerformed
        String htmlStr = htmlEditor.getText();
        HTMLEditorKit kit = new HTMLEditorKit();
        htmlEditor.setEditorKit(kit);

        htmlEditor.setText(htmlStr);
    }//GEN-LAST:event_mnuHtmlActionPerformed

    private void mnuOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuOpenActionPerformed
        int choice = jFileChooser.showOpenDialog(this);
        if (choice == JFileChooser.APPROVE_OPTION) {
            try {
                File pathName = jFileChooser.getSelectedFile();
                
                htmlEditor.setPage(pathName.toURI().toURL());
                
                mnuHtml.setSelected(true);
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_mnuOpenActionPerformed

    private void mnuPlainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPlainActionPerformed
        String htmlStr = htmlEditor.getText();
        StyledEditorKit kit = new StyledEditorKit();
        RTFEditorKit rkit = new RTFEditorKit();
        htmlEditor.setEditorKit(kit);

        htmlEditor.setText(htmlStr);
    }//GEN-LAST:event_mnuPlainActionPerformed

    private void mnuSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSaveActionPerformed
        int choice = jFileChooser.showSaveDialog(this);
        if (choice == JFileChooser.APPROVE_OPTION) {
            try {
                File pathName = jFileChooser.getSelectedFile();
                
                FileWriter fw = new FileWriter(pathName);
                fw.write(htmlEditor.getText());
                fw.flush();
                fw.close();
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_mnuSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JEditorPane htmlEditor;
    private javax.swing.JFileChooser jFileChooser;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButtonMenuItem mnuHtml;
    private javax.swing.JMenuItem mnuOpen;
    private javax.swing.JRadioButtonMenuItem mnuPlain;
    private javax.swing.JMenuItem mnuSave;
    // End of variables declaration//GEN-END:variables
}
